### PR TITLE
allow empty results, fix empty category calculations

### LINKED ISSUE #641: Saving empty flow result fails validation
AttributeError: 'MailroomException' object has no attribute 'f_lineno'

### PR DESCRIPTION
**Pull request by nicpottier**
fixes #641

### CODE REVIEW

File: excellent/functions/builtin_test.go [hunk 1]
```diff
@@ -584,6 +584,7 @@ func TestFunctions(t *testing.T) {
 		{"text_length", dmy, []types.XValue{xs("hello")}, xi(5)},
 		{"text_length", dmy, []types.XValue{xs("")}, xi(0)},
 		{"text_length", dmy, []types.XValue{xs("😁😁")}, xi(2)},
+		{"text_length", dmy, []types.XValue{xs(" 2♣️ ")}, xi(5)},     // emoji color modifier
```
Comment (nicpottier) [inline excellent/functions/builtin_test.go]: sneaking in an assertion as to our behavior around emoji modifiers

File: flows/actions/base_test.go [hunk 2]
```diff
@@ -198,7 +198,12 @@ func testActionType(t *testing.T, assetsJSON json.RawMessage, typeName string, t
 			assert.Equal(t, tc.Inspection.Dependencies, depStrings, "inspected dependencies mismatch in %s", testName)
 
 			results := flow.ExtractResults()
-			assert.Equal(t, tc.Inspection.Results, results, "inspected results mismatch in %s", testName)
+			assert.Equal(t, len(tc.Inspection.Results), len(results), "inspected results mismatch in %s", testName)
+			if len(tc.Inspection.Results) == len(results) {
+				for i := range results {
+					assert.Equal(t, tc.Inspection.Results[i], results[i], "inspected results mismatch in %s")
+				}
+			}
```
Comment (nicpottier) [inline flows/actions/base_test.go]: the higher level test wasn't showing enough detail to figure out the difference, this does

File: flows/actions/set_run_result.go [hunk 3]
```diff
@@ -34,8 +34,8 @@ type SetRunResultAction struct {
 	universalAction
 
 	Name     string `json:"name" validate:"required"`
-	Value    string `json:"value" validate:"required"`
-	Category string `json:"category"`
+	Value    string `json:"value"`
+	Category string `json:"category,omitempty"`
```
Comment (nicpottier) [inline flows/actions/set_run_result.go]: having a category key feels like an optional thing on results

File: flows/actions/set_run_result.go [hunk 4]
```diff
@@ -85,5 +85,9 @@ func (a *SetRunResultAction) RewriteTemplates(localization flows.Localization, r
 
 // EnumerateResults enumerates all potential results on this object
 func (a *SetRunResultAction) EnumerateResults(include func(*flows.ResultSpec)) {
-	include(flows.NewResultSpec(a.Name, []string{a.Category}))
+	if a.Category != "" {
+		include(flows.NewResultSpec(a.Name, []string{a.Category}))
+	} else {
+		include(flows.NewResultSpec(a.Name, nil))
+	}
```
Comment (nicpottier) [inline flows/actions/set_run_result.go]: we were populating possible categories as `[""]` in the no category case
