### PR TITLE
Remove all groups

### LINKED ISSUE #304: Allow flow actions like remove_from_group with no groups?
We sometimes get these in legacy flows but they fail goflow validation

### PR DESCRIPTION
**Pull request by rowanseymour**
Fixes #304

### CODE REVIEW

File: legacy/definition.go [hunk 1]
```diff
@@ -537,6 +537,7 @@ func migrateAction(baseLanguage utils.Language, a Action, localization flows.Loc
 
 		return &actions.RemoveContactGroupsAction{
 			Groups:     groups,
+			AllGroups:  len(groups) == 0,
```
Comment (ericnewcomer) [inline legacy/definition.go]: so old flows represented this as an empty list then?

Comment (rowanseymour) [reply legacy/definition.go]: Yup, checked it
