### PR TITLE
🐌 Remove contacts from broken groups

### LINKED ISSUE #856: ReevaluateDynamicGroups doesn't remove contacts from groups with errors
Opening an issue instead of just fixing it because maybe it requires discussion, but:
  https://github.com/nyaruka/goflow/blob/master/flows/contact.go#L342

Doesn't remove the contact from groups when there are errors in the query for a dynamic group.

Feels like it should, but perhaps this is on purpose?

### PR DESCRIPTION
**Pull request by rowanseymour**
Fixes #856

### CODE REVIEW

File: flows/contact_test.go [hunk 1]
```diff
@@ -186,97 +189,51 @@ func TestContactSetPreferredChannel(t *testing.T) {
...
-
-	males := test.NewGroup("Males", `gender="M"`)
-	tel1800 := test.NewGroup("Tel with 1800", `tel ~ 1800`)
-	twitterCrazies := test.NewGroup("Twitter Crazies", `twitter ~ crazy`)
-	groups := []*flows.Group{males, tel1800, twitterCrazies}
-
-	contact := flows.NewEmptyContact(session.Assets(), "Joe", "eng", nil)
-	contact.AddURN(urns.URN("tel:+12345678999"), nil)
+	for _, tc := range tests {
+		sa, err := engine.NewSessionAssets(source, nil)
```
Comment (rowanseymour) [inline flows/contact_test.go]: Rewriting these tests led me to realize something odd - session assets aren't tied to particular environment - I tried to use the same session assets for each test case.. but.. the parsed contact query of a group is cached on the group. and it is environment specific

That led me to try reworking the whole assets creation thing so that session assets are created with an environment, query parsing happens at group creation (no caching needed)... but then it wasn't obvious how that parse error gets back to the user... so reverted for now.

Comment (nicpottier) [reply flows/contact_test.go]: Is there ever a time in the real world where an environment is different for the same session assets? Not sure I understand. It is very very important to mailroom that Session assets are both thread safe and able to be reused on the same org so we should definitely discuss if that isn't the case.

Comment (rowanseymour) [reply flows/contact_test.go]: No.. this isn't something we do. But it does kinda annoy me that it's possible, but subtly doesn't work correctly because of the cached contact query. Would be nice to get rid of that little bit of caching.
